### ISSUE TITLE
2.2.10 beta fails to start on Nexus 5

### ISSUE THREAD

**Issue by alexolog** [kriztan/Pix-Art-Messenger#398] opened 2019-10-03 15:09 UTC
#### General information

* **Version:** 2.2.10 beta (upgraded from an older version)
* **Device:** Nexus 5
* **Android Version:** Android 6.0.1 Stock

#### Steps to reproduce

1. Launch the app

#### Expected result

App launches

#### Actual result

What do you see instead?

"Unfortunately, Pix-Art Messenger has stopped" right after the logo is shown.
This message sometimes repeats unless I force-stop the app.

#### Debug output
https://pastebin.com/F0WmkjnS

**Comment by alexolog** [comment] 2019-10-03 15:16
Uninstalled.  Installed 2.2.9.  This version works.

**Comment by kriztan** [comment] 2019-10-03 15:50
Thanks @alexolog, I'll fix it

**Comment by kriztan** [comment] 2019-10-09 04:41
This seems not to be a bug of the Messenger. Closing this now. Feel free to reopen it again if you have further information.

**Comment by alexolog** [comment] 2019-10-09 04:48
It happens with the 2.2.10 beta, but not with 2.2.9.
Sounds like a regression to me.

What other information can be provided?

**Comment by kriztan** [comment] 2019-10-09 06:18
Your logfile doesn't contain any exceptions, so I can't check anything. 
I'll check it with the Android Emulator runnig Android 6.0.1 to see if it is reproduceable. If there won't be an issue, it could be a stock rom issue or incompatibility with the new Android X libraries, which should actually be downward compatible.

**Comment by alexolog** [comment] 2019-10-09 06:24
It did contain exceptions, but filtering by "pixart" removed some of the lines.

In particular,
10-03 10:49:46.215 E/AndroidRuntime(10949): 	at de.pixart.messenger.services.ChannelDiscoveryService.<init>(ChannelDiscoveryService.java:40)
10-03 10:49:46.215 E/AndroidRuntime(10949): 	at de.pixart.messenger.services.XmppConnectionService.<init>(XmppConnectionService.java:265)
was a part of the exception trace.

**Comment by kriztan** [comment] 2019-10-09 07:19
The affected lines were not changed between 2.2.9 and 2.2.10 beta.

**Comment by alexolog** [comment] 2019-10-09 22:36
The full stack trace of the exception:

--------- beginning of crash
10-03 09:15:14.737 E/AndroidRuntime(25259): FATAL EXCEPTION: main
10-03 09:15:14.737 E/AndroidRuntime(25259): Process: de.pixart.messenger, PID: 25259
10-03 09:15:14.737 E/AndroidRuntime(25259): java.lang.NoClassDefFoundError: com.google.common.base.Suppliers$SupplierOfInstance
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at com.google.common.base.Suppliers.ofInstance(Suppliers.java:268)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at com.google.common.cache.CacheBuilder.<clinit>(CacheBuilder.java:168)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at de.pixart.messenger.services.ChannelDiscoveryService.<init>(ChannelDiscoveryService.java:40)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at de.pixart.messenger.services.XmppConnectionService.<init>(XmppConnectionService.java:265)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at java.lang.Class.newInstance(Native Method)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2859)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at android.os.Looper.loop(Looper.java:148)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at java.lang.reflect.Method.invoke(Native Method)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-03 09:15:14.737 E/AndroidRuntime(25259): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

If it helps, I usually keep the servers disabled.

**Comment by kriztan** [comment] 2019-10-10 08:33
This seems to be more helpful, thank you, I'll check it.

**Comment by alexolog** [comment] 2019-10-15 21:13
Could you re-open this?  I cannot seem to.

**Closed** 2019-10-19 19:17 UTC
Labels: bug, high priority
