### ISSUE TITLE
Attachment buttons doesn't work

### ISSUE THREAD

**Issue by grinapo** [kriztan/Pix-Art-Messenger#221] opened 2018-07-27 13:41 UTC
#### General information

* **Version:** 2.1.0 beta 2018-07-15
* **Device:** LineageOS 15.1 [oneplus one/bacon]
* **Android Version:** Android 8.1.0 LineageOS

#### Steps to reproduce

1. open a chat
2. press button to attach an image, a photo, a recording, a file
3. nothing really happens [apart from asking for permissions, once]

#### Expected result
Attachment selector popping up, attaching
What is the expected output?

#### Actual result
Nil. Nada. Zilch. Nothing. Keines.

#### Debug output
Nothing relevant.

(07-27 15:38:52.629 D/Pix-Art_Messenger(14254): All permissions granted, starting Pix-Art Messenger(1532696441380))

**Comment by grinapo** [comment] 2018-07-28 07:44
(Update based on chat) It is using my private server (prosody) with upstream included features. However Conversations is able to attach while PixArtIM cannot.

**Comment by kriztan** [comment] 2018-07-28 08:12
I can't reproduce this. Please provide more information and full adb logs. Otherwise I can't help you.

**Comment by kriztan** [comment] 2018-08-03 21:10
No reaction from issuer... closing this

**Closed by kriztan** 2018-08-03 21:10 UTC

**Comment by grinapo** [comment] 2018-08-06 08:31
Okay. I already mentioned in the supportchat that adb logs did not contain _anything_ useful, and asked you whether it may be an error in the feature detection.

**Comment by github-tomster** [comment] 2018-09-08 14:09
got a log, comming later

**Comment by github-tomster** [comment] 2018-09-10 21:19
is the log helpful?

**Comment by grinapo** [comment] 2018-09-17 09:07
Just mentioning that this bug is **closed**, so you possibly will not see notifications. As this one. :-P

**Comment by github-tomster** [comment] 2018-09-17 09:17
notifiactions work, no matter if open or closed :-)

**Comment by github-tomster** [comment] 2018-09-17 10:14
nice.
i will check the code of conversations and pix-art, sxs
so it shall highlight why pix-art fails and conversations dont.

btw: 
if i go the reverse way,
selecting a file and choose 'share via pix-art'
it works ...

**Comment by kriztan** [comment] 2019-01-07 09:43
Welcome 2019, too. 
You cannot generally say that this is a bug on los based ROMs, because I'm also using los and it's working as expected. Have you tried a los update?

**Comment by github-tomster** [comment] 2019-01-07 09:48
the aokp rom is build 2018-12-31
i flashed only the rom and installed pixart. nothing more. and it does not work :-(
then tried conversations and it worked.

**Comment by github-tomster** [comment] 2019-01-07 23:03
for the last test, a few days ago, i used the one from github 2.1.5.
as i wrote: nothing more was installed on the rom so i installed from sd-card.
i'll try to kontakt.

**Comment by kriztan** [comment] 2019-01-08 20:43
@github-tomster I can't contact you via xmpp... I can't connect to you server, is it offline?

**Comment by github-tomster** [comment] 2019-01-08 22:04
@grinapo
there is hope. i guess kriztan figured it out.

**Comment by grinapo** [comment] 2019-01-09 07:05
Halleljua! Vishnu is great! :-) 
Maybe he'd even reopen this issue! ;-)

**Comment by kriztan** [comment] 2019-01-09 07:07
Seems to be fixed in 63b800fabe3ea48595844643e653212c6ff61fa7

**Comment by guigri** [comment] 2019-03-04 19:44
I just installed the messenger version 2.1.5 from Play Store on to different Android devices and I do have the same problems on both devices.
The bug is supposed to be fixed in version 2.2.0 beta 3. When will the final version 2.2.0 be available? Is there any road map available?
Thank you.

**Comment by kriztan** [comment] 2019-03-04 19:51
I'm going to fix some issues and will push the final version soon. There is no roadmap, I'll work on it if my freetime allows it.
