### ISSUE TITLE
add exit button

### ISSUE THREAD

**Issue by OmlineEditor** [kriztan/Pix-Art-Messenger#400] opened 2019-10-14 18:16 UTC
I ask you to add a full exit button to the main menu (disconnecting from the server and closing the service that is in memory). I don’t want the program to be constantly in memory. I want to close it when I do not need it.

**Comment by kriztan** [comment] 2019-10-14 18:24
It's not supposed to close and exit the app completely. As workaround activate the multi account mode in expert settings. This will give you the possibility to disconnect the account in account settings.

**Comment by kriztan** [comment] 2019-10-14 18:25
Duplicate of #290

**Closed by kriztan** 2019-10-14 18:24 UTC

**Comment by OmlineEditor** [comment] 2019-10-14 18:40
This is not a convenient way. this is a crutch to solve a problem. other programs all have a button to exit you do not have it. please add.

**Comment by kriztan** [comment] 2019-10-14 18:43
There won't be an exit button.

**Comment by OmlineEditor** [comment] 2019-10-14 19:40
why? where is the logic? if I don’t want to use the program, I want to completely close it and exit my account, why should I not be able to do this in an intuitive way? all programs have an exit button, only you don't have one.

**Comment by kriztan** [comment] 2019-10-15 06:57
The core feature of a messenger is to receive messages at any time, also if the messenger is not visible. An exit button will break this.

**Comment by OmlineEditor** [comment] 2019-10-15 13:51
I know it. I need this. I need to stop receiving messages. let's then rename the button to "All disconnect and full exit". so it will be clearer. you can still make a setting with the explanation that the default button does not show the exit button and if necessary it can be separately shown in the main menu. OK?

**Comment by kriztan** [comment] 2019-10-15 14:07
I won't implement this. I've shown you a workaround which is working well for thousands of users. This will be good for you too. I'll finally lock this conversation now, because everything is told.
