### ISSUE TITLE
Add ability to "quote/cite" (comment on) images or any other files

### ISSUE THREAD

**Issue by bennypr0fane** [kriztan/Pix-Art-Messenger#489] opened 2020-05-17 21:09 UTC
#### General information

In PAM 2.4, users can quote messages (using `>` or the "quote/cite" button) from further back in chat history to indicate that a message is a reaction not to the one directly above it, but to something written earlier on.
The same is not possible with images. If I want to comment on an image that was posted further up, I have to somehow make reference using words.
Especially in MUC where images are frequently submitted, reactions can often come late to the party, and here it would be a big improvement to have the "quote/cite" functionality available as well (possibly labelled "comment" instead of "quote/cite"). Ideally, this would work for any file type, not just images.

**Comment by Echolon** [comment] 2020-05-25 22:36
duplicate of #430

**Closed by Echolon** 2020-05-25 22:36 UTC
Labels: Enhancement, UI
