### ISSUE TITLE
Idea: lock app with pin

### ISSUE THREAD

**Issue by Bondarz** [kriztan/Pix-Art-Messenger#429] opened 2020-01-19 18:16 UTC
Hello, is it possible to lock/unlock the app with a pin, password or fingerprint?

Thanks

**Comment by kriztan** [comment] 2020-01-19 19:04
Duplicate of #313

**Comment by Echolon** [comment] 2020-01-23 20:38
@Bondarz 

I think you can lock apps per app already from Android side.

However, I will close with reference to the previous post.

**Closed by Echolon** 2020-01-23 20:38 UTC
